language: node_js
node_js:
  - '12'
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --base-href https://faastener.github.io/faastener/
  - npm run build:doc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/apps/documentation/
  on:
    branch: master
