import {CriterionInstance} from './classification';

/**
 * An interface representing the review data which comprises [CriterionInstances]{@link CriterionInstance} related to a particular technology.
 */
export interface TechnologyDossier {
  /**
   * Unique technology identifier.
   */
  id: string;

  /**
   * Technology name.
   */
  technologyName: string;

  /**
   * Date of review.
   */
  reviewDate?: Date;

  /**
   * Technology for comparison.
   */
  technologyInfo: TechnologyInfo;

  /**
   * A set of CriterionInstance {@link CriterionInstance} encompassing the review data.
   */
  reviewedCriteria: Set<CriterionInstance>;
}

/**
 * An interface representing an information block about the technology for comparison.
 *
 * @example a FaaS platform
 */
export interface TechnologyInfo {
  /**
   * [Type]{@link TechnologyType} this technology belongs to.
   *
   * @example
   * Function-as-a-Service platforms
   */
  technologyType: TechnologyType;

  /**
   * A string value that can be used by the {@link LogoLocatorService} to locate the technology logo.
   *
   * @example
   * azure.functions for Azure Functions,
   * aws.s3 for AWS S3
   */
  logoLocator: string;

  /**
   * Technology logo location path generated by the {@link LogoLocatorService}.
   */
  logoLocation?: string;

  /**
   * Short description shown in technology lists.
   */
  shortDescription?: string;

  /**
   * Full description shown in technology details.
   */
  description?: string;
}

/**
 * An enum representing different technology categories.
 *
 * @example
 * faas for Function-as-a-Service
 * baas for Blockchain-as-a-Service
 */
export enum TechnologyType {
  faas = 'faas', baas = 'baas'
}
