import {CriterionInstance} from './classification';

/**
 * An interface representing a technology for comparison,
 * which might contain the review data in a form of a {@link TechnologyDossier}.
 *
 * @example a FaaS platform
 */
export interface Technology {
  /**
   * Unique technology identifier.
   */
  id: string;

  /**
   * Technology name.
   */
  platformName: string;

  /**
   * [Category]{@link TechnologyCategory} this technology belongs to.
   *
   * @example
   * Function-as-a-Service platforms
   */
  category: TechnologyCategory;

  /**
   * A string value that can be used by the {@link LogoLocatorService} to locate the technology logo.
   *
   * @example
   * azure.functions for Azure Functions,
   * aws.s3 for AWS S3
   */
  logoLocator: string;

  /**
   * Technology logo location path generated by the {@link LogoLocatorService}.
   */
  logoLocation?: string;

  /**
   * Short description shown in technology lists.
   */
  shortDescription?: string;

  /**
   * Full description shown in technology details.
   */
  description?: string;

  /**
   * A [TechnologyDossier]{@link TechnologyDossier} storing the review data.
   */
  dossier?: TechnologyDossier;
}

/**
 * An interface representing the review data which comprises [CriterionInstances]{@link CriterionInstance} related to a particular technology.
 */
export interface TechnologyDossier {
  /**
   * Unique technology identifier.
   */
  platformId: string;

  /**
   * Date of review.
   */
  reviewDate?: Date;

  /**
   * A map of CriterionInstance unique IDs and {@link CriterionInstance} encompassing the review data.
   */
  reviewedCriteria: Map<string, CriterionInstance>;
}

/**
 * An enum representing different technology categories.
 *
 * @example
 * faas for Function-as-a-Service
 * baas for Blockchain-as-a-Service
 */
export enum TechnologyCategory {
  faas = 'faas', baas = 'baas'
}
